version: "3.9"

services:
  web:
    build: .
    container_name: "flask"
    ports:
      - "5432:5432"
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydatabase"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - ./app:/app

  mongo:
    container_name: "mongo"
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo_data:
